stages:
    - test
    - deploy

Backend_Workers_Testing:
    stage: test
    image: node:22-alpine
    script:
        - cd cafe-coffee-backend
        - npm ci
    rules:
        - changes:
            - cafe-coffee-backend/**/*


Frontend:
    stage: test
    image: node:22-alpine
    script:
        - cd frontend
        - npm ci
        - npm run lint
        - npm run build
    rules:
        - changes:
            - frontend/**/*


Backend_Workers_Deploy:
    stage: deploy
    image: node:22-alpine
    script:
        - cd cafe-coffee-backend
        - npm ci
        - npx wrangler deploy
    only: 
        - main
    rules:
        - if: '$CI_COMMIT_BRANCH == "main"'
          changes:
            - cafe-coffee-backend/**/*
            

